# Generated by Django 4.2.13 on 2024-06-04 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0003_remove_answer_disliked_by_remove_answer_liked_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='topic',
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='topic.topic'),
            preserve_default=False,
        ),
    ]
